ALTER TABLE users ADD COLUMN phone_number VARCHAR(20);
ALTER TABLE users ADD COLUMN email VARCHAR(50);
ALTER TABLE users ADD COLUMN account_non_locked BOOLEAN DEFAULT TRUE,
ADD COLUMN failed_attempts INT DEFAULT 0,
ADD COLUMN lock_time TIMESTAMP;