spring.application.name=payment-gateway
server.port=9002

spring.datasource.url=jdbc:postgresql://localhost:5432/leapmoney
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

razorpay.api.key=rzp_test_SmmOkqS39GTI7I
razorpay.api.secret=KrhHX90pgCD50qBcMpQYOrnU
